# Generated by Django 2.1.1 on 2018-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('Title', models.CharField(max_length=120)),
                ('Author', models.CharField(max_length=120)),
                ('Publisher', models.CharField(max_length=120)),
                ('Image', models.CharField(max_length=500)),
            ],
        ),
    ]
