# Generated by Django 2.1.1 on 2019-01-02 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20181213_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='Sample Info About The Book working on it', max_length=500),
        ),
        migrations.AddField(
            model_name='book',
            name='pc',
            field=models.IntegerField(default=245),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='ED',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 16, 59, 6, 264617)),
        ),
    ]
